### ISSUE TITLE
failed to run rake cloudwatch_scheduler:setup

### ISSUE THREAD

**Issue by pritambios** [paul/cloudwatch_scheduler#15]
I am facing this issue. 
```
rake aborted!
NameError: uninitialized constant ApplicationJob
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/cloudwatch_scheduler-1.1.1/lib/cloudwatch_scheduler/job.rb:4:in `<module:CloudwatchScheduler>'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/cloudwatch_scheduler-1.1.1/lib/cloudwatch_scheduler/job.rb:3:in `<main>'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/cloudwatch_scheduler-1.1.1/lib/cloudwatch_scheduler/engine.rb:8:in `block in <class:Engine>'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `instance_exec'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `run'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/railties-7.0.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/railties-7.0.3.1/lib/rails/initializable.rb:60:in `run_initializers'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/railties-7.0.3.1/lib/rails/application.rb:372:in `initialize!'
/Users/user/dev/demo-app/config/environment.rb:15:in `<main>'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/railties-7.0.3.1/lib/rails/application.rb:348:in `require_environment!'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/railties-7.0.3.1/lib/rails/application.rb:511:in `block in run_tasks_blocks'
/Users/user/.rbenv/versions/2.7.6/gemsets/demo-app/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => cloudwatch_scheduler:setup => environment
```

**Comment by pritambios** [comment]
if I use this in my gemfile I am able to make it work. :)
`gem "cloudwatch_scheduler", github: "paul/cloudwatch_scheduler"`
